import '../globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <div style={{ height: "50px", width: "100%", background: "green"}}></div> */}
      <body className={inter.className}>{children}</body>
      {/* <div style={{ height: "50px", width: "100%", background: "red"}}></div> */}
    </html>
  )
}
